config/routes.rb
Rails.application.routes.draw do
  resources :themes
  resources :images
  resources :values
  resources :users
  resources :sessions
  get 'main/index'
  get 'main/help'
  get 'main/contacts'
  get 'main/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'main#index'
  match 'work', to: 'work#index', via: :get
  match 'choose_theme', to: 'work#choose_theme', via: :get
  match 'display_theme', to: 'work#display_theme', via: :post
  get 'api/next_image' => 'api#next_image'
  get 'api/prev_image' => 'api#prev_image'
  get 'api/save_value' => 'api#save_value'
  match 'signup',   to: 'users#new',            via: 'get'
  match 'signin',   to: 'sessions#new',         via: 'get'
  match 'signout',  to: 'sessions#destroy',     via: 'get'
  match 'results',     to: 'work#results', via: :get
end

app/views/shared/_footer.html.erb
<footer>
    <a href="http://rubyonrails.org">Ruby on Rails Website</a></li>
</footer>

app/views/shared/_header.html.haml
%body
  %header
    %nav.navbar.navbar-expand-lg.bg-body
      .container-fluid
        %button.navbar-toggler{"aria-controls" => "navbarExample01", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-mdb-collapse-init" => "", "data-mdb-target" => "#navbarExample01", type: "button"}
          %i.fas.fa-bars
        #navbarExample01.collapse.navbar-collapse
          %ul.navbar-nav.me-auto.mb-2.mb-lg-0
            %li.nav-item.active
              = link_to t('.home'), root_path, :class => "nav-link"
            %li.nav-item
              %a.nav-link{:href => "/main/contacts"} Contacts
            %li.nav-item
              %a.nav-link{:href => "/main/help"} Help
            %li.nav-item
              %a.nav-link{:href => "/main/about"} About

            - if signed_in?
              %li= link_to "Results", results_path, :class => "nav-link"
              %li= link_to t('.sign_out'), signout_path, :class => "nav-link"
              %li.logged.nav-link
                = current_user.email
                = current_user.name
                %img{ src: "https://secure.gravatar.com/avatar/#{Digest::MD5.hexdigest(current_user.email)}.png", style: "width: 25px;" }
            - else
              %li= link_to t('.sign_in'), signin_path, :class => "nav-link"

          .locale
            .ru_link
              = link_to image_tag("pictures/rus.jpg", alt: "",  style: "width: 30px; margin-right: 5px", title: "Русский" ), locale: :ru
            .en_link
              = link_to image_tag("pictures/uk.jpg", alt: "",  style: "width: 30px; margin-right: 5px", title: "English"), locale: :en
            %b
              = I18n.locale